//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthenticationUser
    {
        public int Authuserid { get; set; }
        public string UserAdmin { get; set; }
        public string UserAccess { get; set; }
        public string EmailId { get; set; }
        public string Verification { get; set; }
        public string AccessType { get; set; }
        public string UserAdminName { get; set; }
    }
}
